import type { LessonQuizQuestion } from "../src/lib/supabase/database.types";

export interface LessonSeed {
  slug: string;
  title: string;
  description: string;
  cefr_level: "A1" | "A2" | "B1" | "B2";
  order_index: number;
  intro_text: string;
  word_slugs: string[];
  grammar_topic_slug?: string;
  grammar_tip?: string;
  grammar_examples?: string[];
  quiz_questions: LessonQuizQuestion[];
  xp_reward: number;
  estimated_minutes: number;
  published: boolean;
}

function defaultQuiz(lessonTitle: string): LessonQuizQuestion[] {
  const t = lessonTitle;
  return [
    {
      question: `Which best describes the focus of “${t}”?`,
      options: ["Core vocabulary and patterns for this topic", "Advanced physics", "Cooking recipes", "Sports rules"],
      correct_index: 0,
      explanation: "The lesson centers on practical English for this theme.",
    },
    {
      question: "Choose the sentence with correct use of “a” / “an”.",
      options: [
        "She is a university student.",
        "She is an university student.",
        "She is university student.",
        "She is an student.",
      ],
      correct_index: 0,
      explanation: "“University” starts with a /juː/ consonant sound — use “a”.",
    },
    {
      question: "Which word is a verb?",
      options: ["quickly", "happy", "run", "beauty"],
      correct_index: 2,
      explanation: "“Run” is a verb; the others are adverb, adjective, noun.",
    },
    {
      question: "Pick the polite request.",
      options: ["Give me water.", "Could I have some water, please?", "Water now.", "You get water."],
      correct_index: 1,
      explanation: "“Could I… please?” is a natural polite request.",
    },
    {
      question: "Which sentence is in the present simple?",
      options: ["I am studying now.", "She walks to work.", "They had left.", "We will go."],
      correct_index: 1,
      explanation: "“She walks” is present simple for a habit.",
    },
  ];
}

export const LESSONS: LessonSeed[] = [
  {
    slug: "a1-lesson-1-greetings",
    title: "Greetings and Introductions",
    description:
      "Learn how to say hello, introduce yourself, and ask basic questions.",
    cefr_level: "A1",
    order_index: 1,
    intro_text:
      "Welcome to your first lesson! In this 5-minute session, you'll learn 5 essential greeting words, master a simple grammar rule, and practice with a quick quiz. Let's begin!",
    word_slugs: ["hello", "name", "good", "morning", "friend"],
    grammar_topic_slug: "articles-a-an-the",
    grammar_tip:
      "Use 'a' before consonants and 'an' before vowels. This is the simplest rule to know.",
    grammar_examples: [
      "She is a teacher.",
      "He is an engineer.",
      "I have a friend.",
      "There is an apple on the table.",
    ],
    quiz_questions: [
      {
        question: "What does 'hello' mean?",
        options: ["A greeting", "A farewell", "A question", "A food"],
        correct_index: 0,
        explanation: "'Hello' is the most common English greeting.",
      },
      {
        question: "Choose the correct: 'She is ___ doctor.'",
        options: ["a", "an", "the", "no article"],
        correct_index: 0,
        explanation: "'Doctor' starts with a consonant sound, so we use 'a'.",
      },
      {
        question: "What's the opposite of 'good morning'?",
        options: ["Good afternoon", "Good night", "Goodbye", "Hello"],
        correct_index: 1,
        explanation: "'Good night' is typically said before bed or when parting at night.",
      },
      {
        question: "Complete: 'Nice to meet ___.'",
        options: ["you", "me", "she", "it"],
        correct_index: 0,
        explanation: "'Nice to meet you' is a common English greeting when meeting someone new.",
      },
      {
        question: "Which sentence is correct?",
        options: ["I have a friend.", "I have an friend.", "I have friend.", "I have the friend."],
        correct_index: 0,
        explanation: "'Friend' starts with consonant sound, so use 'a', not 'an'.",
      },
    ],
    xp_reward: 30,
    estimated_minutes: 5,
    published: true,
  },
  {
    slug: "a1-lesson-2-numbers",
    title: "Numbers and Counting",
    description: "Master numbers from 1 to 20 and learn how to count in English.",
    cefr_level: "A1",
    order_index: 2,
    intro_text:
      "Numbers are the foundation of so many conversations. Let's learn the essential numbers and how to use them in simple sentences.",
    word_slugs: ["one", "two", "three", "four", "five"],
    grammar_topic_slug: "articles-a-an-the",
    grammar_tip:
      "When counting, we use singular for 'one' and plural for numbers above one: 'one book', 'two books'.",
    grammar_examples: [
      "I have one apple.",
      "She has two cats.",
      "There are three chairs.",
      "He bought four tickets.",
    ],
    quiz_questions: [
      {
        question: "What comes after 'three'?",
        options: ["two", "four", "five", "one"],
        correct_index: 1,
        explanation: "The sequence is: one, two, three, four, five...",
      },
      {
        question: "Which is correct: 'I have ___ books.'",
        options: ["one", "two", "a", "an"],
        correct_index: 1,
        explanation: "With plural 'books', we need a plural number like 'two'.",
      },
      {
        question: "How do you say '5' in English?",
        options: ["four", "five", "fifteen", "fifty"],
        correct_index: 1,
        explanation: "'5' is 'five'.",
      },
      {
        question: "Complete: 'She has ___ cat.'",
        options: ["one", "two", "three", "a"],
        correct_index: 0,
        explanation: "Singular 'cat' pairs with 'one' (or 'a').",
      },
      {
        question: "What is 'two + two'?",
        options: ["three", "four", "five", "six"],
        correct_index: 1,
        explanation: "2 + 2 = 4 (four).",
      },
    ],
    xp_reward: 30,
    estimated_minutes: 5,
    published: true,
  },
  {
    slug: "a1-lesson-3-family",
    title: "Family Members",
    description: "Learn the names for family members and how to talk about your family.",
    cefr_level: "A1",
    order_index: 3,
    intro_text:
      "Family is universal. Let's learn the essential family vocabulary so you can talk about yours.",
    word_slugs: ["family", "parent", "friend", "child", "house"],
    grammar_topic_slug: "articles-a-an-the",
    grammar_tip:
      "We use 'my' to show possession: 'my mother', 'my brother'. For general statements, we use 'a' or 'the'.",
    grammar_examples: [
      "My mother is a doctor.",
      "Her father is kind.",
      "We have a big family.",
      "The family lives together.",
    ],
    quiz_questions: [
      {
        question: "What is 'parent'?",
        options: ["A child", "A mother or father", "A friend", "A teacher"],
        correct_index: 1,
        explanation: "'Parent' means a mother or father.",
      },
      {
        question: "Complete: 'She has ___ children.'",
        options: ["a", "an", "two", "the"],
        correct_index: 2,
        explanation: "'Children' is plural, so use a number like 'two'.",
      },
      {
        question: "What's another word for 'home'?",
        options: ["house", "family", "friend", "school"],
        correct_index: 0,
        explanation: "'House' and 'home' are similar — both places where you live.",
      },
      {
        question: "Which is correct?",
        options: ["I have a family.", "I have an family.", "I have family.", "I have the family."],
        correct_index: 0,
        explanation: "'Family' starts with consonant sound, use 'a'.",
      },
      {
        question: "A young person is called a...",
        options: ["parent", "child", "friend", "family"],
        correct_index: 1,
        explanation: "A young person is a 'child'.",
      },
    ],
    xp_reward: 30,
    estimated_minutes: 5,
    published: true,
  },
  {
    slug: "a1-lesson-4-colors",
    title: "Colors",
    description: "Name common colors and use them in short sentences.",
    cefr_level: "A1",
    order_index: 4,
    intro_text: "Colors help you describe the world. Learn five essential color words.",
    word_slugs: ["red", "blue", "green", "yellow", "white"],
    grammar_topic_slug: "comparatives-superlatives",
    grammar_tip: "We say “a red car” with adjective before noun: color + noun.",
    grammar_examples: ["The sky is blue.", "Grass is green.", "Snow is white."],
    quiz_questions: defaultQuiz("Colors"),
    xp_reward: 30,
    estimated_minutes: 5,
    published: true,
  },
  {
    slug: "a1-lesson-5-food-basics",
    title: "Food Basics",
    description: "Talk about simple foods and meals.",
    cefr_level: "A1",
    order_index: 5,
    intro_text: "Food vocabulary opens daily conversations — from breakfast to dinner.",
    word_slugs: ["food", "water", "eat", "bread", "coffee"],
    grammar_topic_slug: "articles-a-an-the",
    grammar_tip: "Use uncountable nouns without “a”: water, bread (general).",
    grammar_examples: ["I drink water.", "We eat bread.", "I like coffee."],
    quiz_questions: defaultQuiz("Food Basics"),
    xp_reward: 30,
    estimated_minutes: 5,
    published: true,
  },
  {
    slug: "a1-lesson-6-time",
    title: "Time Words",
    description: "Say today, tomorrow, and talk about parts of the day.",
    cefr_level: "A1",
    order_index: 6,
    intro_text: "Time words help you plan and describe your routine.",
    word_slugs: ["time", "day", "today", "tomorrow", "morning"],
    grammar_topic_slug: "prepositions-time-place",
    grammar_tip: "Use “in the morning”, “at night” — prepositions matter.",
    grammar_examples: ["I study in the morning.", "See you tomorrow.", "Today is busy."],
    quiz_questions: defaultQuiz("Time Words"),
    xp_reward: 30,
    estimated_minutes: 5,
    published: true,
  },
  {
    slug: "a1-lesson-7-calendar",
    title: "Days and Weeks",
    description: "Talk about the week, month, and year.",
    cefr_level: "A1",
    order_index: 7,
    intro_text: "Organize plans with calendar vocabulary.",
    word_slugs: ["day", "week", "month", "year", "weekend"],
    grammar_topic_slug: "prepositions-time-place",
    grammar_tip: "Say “on the weekend” (US) or “at the weekend” (UK).",
    grammar_examples: ["This week is short.", "Happy weekend!", "See you next month."],
    quiz_questions: defaultQuiz("Days and Weeks"),
    xp_reward: 30,
    estimated_minutes: 5,
    published: true,
  },
  {
    slug: "a1-lesson-8-weather",
    title: "Weather",
    description: "Describe sun, rain, and wind in simple English.",
    cefr_level: "A1",
    order_index: 8,
    intro_text: "Weather is a classic small-talk topic.",
    word_slugs: ["weather", "rain", "sun", "wind", "cold"],
    grammar_topic_slug: "present-perfect",
    grammar_tip: "Present simple for facts: “It rains a lot here.”",
    grammar_examples: ["It is cold today.", "The sun is bright.", "Strong wind!"],
    quiz_questions: defaultQuiz("Weather"),
    xp_reward: 30,
    estimated_minutes: 5,
    published: true,
  },
  {
    slug: "a1-lesson-9-body",
    title: "Body Parts",
    description: "Name basic body parts for health and descriptions.",
    cefr_level: "A1",
    order_index: 9,
    intro_text: "Useful words for health, sports, and everyday life.",
    word_slugs: ["body", "head", "hand", "eye", "foot"],
    grammar_topic_slug: "articles-a-an-the",
    grammar_tip: "“My head hurts” — possessive + body part.",
    grammar_examples: ["I wash my hands.", "She has blue eyes.", "My foot hurts."],
    quiz_questions: defaultQuiz("Body Parts"),
    xp_reward: 30,
    estimated_minutes: 5,
    published: true,
  },
  {
    slug: "a1-lesson-10-places",
    title: "Places in Town",
    description: "Talk about home, school, and the city.",
    cefr_level: "A1",
    order_index: 10,
    intro_text: "Find your way around common places.",
    word_slugs: ["place", "home", "school", "city", "house"],
    grammar_topic_slug: "prepositions-time-place",
    grammar_tip: "“At school” vs “in the city” — learn fixed phrases.",
    grammar_examples: ["I live in the city.", "She is at school.", "Welcome home."],
    quiz_questions: defaultQuiz("Places in Town"),
    xp_reward: 30,
    estimated_minutes: 6,
    published: true,
  },
  {
    slug: "a2-lesson-11-routine",
    title: "Daily Routine",
    description: "Describe your typical day with simple present.",
    cefr_level: "A2",
    order_index: 11,
    intro_text: "Share habits and schedules clearly.",
    word_slugs: ["morning", "evening", "breakfast", "dinner", "sleep"],
    grammar_topic_slug: "present-perfect",
    grammar_tip: "Present simple for routines: “I usually start work at nine.”",
    grammar_examples: ["I eat breakfast at 7.", "We cook dinner together.", "I sleep early."],
    quiz_questions: defaultQuiz("Daily Routine"),
    xp_reward: 40,
    estimated_minutes: 6,
    published: true,
  },
  {
    slug: "a2-lesson-12-shopping",
    title: "Shopping",
    description: "Ask prices, compare, and pay.",
    cefr_level: "A2",
    order_index: 12,
    intro_text: "Handle shops and markets with confidence.",
    word_slugs: ["shop", "buy", "money", "price", "discount"],
    grammar_topic_slug: "comparatives-superlatives",
    grammar_tip: "Cheaper / more expensive — compare products.",
    grammar_examples: ["This jacket is cheaper.", "How much is it?", "I pay by card."],
    quiz_questions: defaultQuiz("Shopping"),
    xp_reward: 40,
    estimated_minutes: 6,
    published: true,
  },
  {
    slug: "a2-lesson-13-transport",
    title: "Transportation",
    description: "Talk about cars, buses, and travel by road.",
    cefr_level: "A2",
    order_index: 13,
    intro_text: "Move around town and plan trips.",
    word_slugs: ["car", "bus", "train", "station", "road"],
    grammar_topic_slug: "future-will-vs-going-to",
    grammar_tip: "“I’m going to take the bus” for a plan.",
    grammar_examples: ["The train is late.", "We drive on this road.", "Meet me at the station."],
    quiz_questions: defaultQuiz("Transportation"),
    xp_reward: 40,
    estimated_minutes: 6,
    published: true,
  },
  {
    slug: "a2-lesson-14-hobbies",
    title: "Hobbies",
    description: "Discuss music, reading, and sports.",
    cefr_level: "A2",
    order_index: 14,
    intro_text: "Say what you enjoy in your free time.",
    word_slugs: ["music", "read", "write", "sport", "game"],
    grammar_topic_slug: "gerunds-and-infinitives",
    grammar_tip: "“I enjoy reading” uses gerund after enjoy.",
    grammar_examples: ["I love music.", "She writes every day.", "We play football."],
    quiz_questions: defaultQuiz("Hobbies"),
    xp_reward: 40,
    estimated_minutes: 6,
    published: true,
  },
  {
    slug: "a2-lesson-15-past-events",
    title: "Past Events",
    description: "Use past time words and simple past ideas.",
    cefr_level: "A2",
    order_index: 15,
    intro_text: "Tell short stories about yesterday and last week.",
    word_slugs: ["yesterday", "last", "time", "day", "year"],
    grammar_topic_slug: "past-continuous",
    grammar_tip: "Past simple for finished actions: “I visited Paris last year.”",
    grammar_examples: ["Yesterday was busy.", "Last week I rested.", "That day was fun."],
    quiz_questions: defaultQuiz("Past Events"),
    xp_reward: 40,
    estimated_minutes: 6,
    published: true,
  },
  {
    slug: "a2-lesson-16-future-plans",
    title: "Future Plans",
    description: "Talk about goals with will and going to.",
    cefr_level: "A2",
    order_index: 16,
    intro_text: "Share plans for tomorrow and beyond.",
    word_slugs: ["tomorrow", "plan", "goal", "idea", "test"],
    grammar_topic_slug: "future-will-vs-going-to",
    grammar_tip: "Going to for intentions; will for quick decisions.",
    grammar_examples: ["I will call you.", "We’re going to travel.", "My goal is clear."],
    quiz_questions: defaultQuiz("Future Plans"),
    xp_reward: 40,
    estimated_minutes: 6,
    published: true,
  },
  {
    slug: "a2-lesson-17-descriptions",
    title: "Descriptions",
    description: "Use adjectives to describe people and things.",
    cefr_level: "A2",
    order_index: 17,
    intro_text: "Make your speaking more vivid with better adjectives.",
    word_slugs: ["big", "small", "beautiful", "interesting", "different"],
    grammar_topic_slug: "comparatives-superlatives",
    grammar_tip: "Order: opinion before size — “a beautiful big house”.",
    grammar_examples: ["She is kind.", "It’s an interesting book.", "Two different ideas."],
    quiz_questions: defaultQuiz("Descriptions"),
    xp_reward: 40,
    estimated_minutes: 6,
    published: true,
  },
  {
    slug: "a2-lesson-18-emotions",
    title: "Emotions",
    description: "Express feelings from happy to worried.",
    cefr_level: "A2",
    order_index: 18,
    intro_text: "Talk about emotions in everyday life.",
    word_slugs: ["happy", "sad", "angry", "worried", "excited"],
    grammar_topic_slug: "modals-possibility",
    grammar_tip: "“I might be late” — modal + base verb.",
    grammar_examples: ["I feel happy.", "She looks worried.", "We’re excited."],
    quiz_questions: defaultQuiz("Emotions"),
    xp_reward: 40,
    estimated_minutes: 6,
    published: true,
  },
  {
    slug: "a2-lesson-19-health",
    title: "Health",
    description: "Doctor visits, medicine, and feeling ill.",
    cefr_level: "A2",
    order_index: 19,
    intro_text: "Essential phrases for health situations.",
    word_slugs: ["doctor", "medicine", "hospital", "pain", "illness"],
    grammar_topic_slug: "modals-obligation",
    grammar_tip: "“You should rest” — modal for advice.",
    grammar_examples: ["I need medicine.", "The doctor helps.", "I have a pain in my head."],
    quiz_questions: defaultQuiz("Health"),
    xp_reward: 40,
    estimated_minutes: 6,
    published: true,
  },
  {
    slug: "a2-lesson-20-directions",
    title: "Directions",
    description: "Ask where places are and understand simple directions.",
    cefr_level: "A2",
    order_index: 20,
    intro_text: "Navigate streets and landmarks.",
    word_slugs: ["direction", "street", "road", "side", "station"],
    grammar_topic_slug: "prepositions-time-place",
    grammar_tip: "“Turn right at the station” — imperatives for directions.",
    grammar_examples: ["Go straight.", "It is on the left.", "Cross the road."],
    quiz_questions: defaultQuiz("Directions"),
    xp_reward: 40,
    estimated_minutes: 6,
    published: true,
  },
  {
    slug: "b1-lesson-21-work",
    title: "Work and Career",
    description: "Discuss jobs, meetings, and projects.",
    cefr_level: "B1",
    order_index: 21,
    intro_text: "Professional vocabulary for the workplace.",
    word_slugs: ["work", "meeting", "project", "email", "career"],
    grammar_topic_slug: "present-perfect",
    grammar_tip: "Present perfect for experience: “I have worked here for two years.”",
    grammar_examples: ["The meeting starts soon.", "We finished the project.", "Check your email."],
    quiz_questions: defaultQuiz("Work and Career"),
    xp_reward: 50,
    estimated_minutes: 7,
    published: true,
  },
  {
    slug: "b1-lesson-22-travel",
    title: "Travel Experiences",
    description: "Hotels, airports, and trips abroad.",
    cefr_level: "B1",
    order_index: 22,
    intro_text: "Share travel stories with richer verbs.",
    word_slugs: ["travel", "hotel", "airport", "ticket", "vacation"],
    grammar_topic_slug: "past-continuous",
    grammar_tip: "Past continuous for background: “While I was waiting, the flight was delayed.”",
    grammar_examples: ["We stayed at a hotel.", "The airport was crowded.", "I lost my ticket."],
    quiz_questions: defaultQuiz("Travel Experiences"),
    xp_reward: 50,
    estimated_minutes: 7,
    published: true,
  },
  {
    slug: "b1-lesson-23-opinions",
    title: "Giving Opinions",
    description: "Agree, disagree, and suggest politely.",
    cefr_level: "B1",
    order_index: 23,
    intro_text: "Take part in discussions with clear opinions.",
    word_slugs: ["opinion", "suggest", "agree", "disagree", "however"],
    grammar_topic_slug: "reported-speech",
    grammar_tip: "Softeners: “I’m not sure, but…”",
    grammar_examples: ["In my opinion…", "I partly agree.", "However, there is a risk."],
    quiz_questions: defaultQuiz("Giving Opinions"),
    xp_reward: 50,
    estimated_minutes: 7,
    published: true,
  },
  {
    slug: "b1-lesson-24-conditionals",
    title: "First Conditional",
    description: "Talk about real possibilities with if.",
    cefr_level: "B1",
    order_index: 24,
    intro_text: "Connect conditions and results.",
    word_slugs: ["help", "study", "test", "exam", "learn"],
    grammar_topic_slug: "first-conditional",
    grammar_tip: "If + present, will + verb for likely future results.",
    grammar_examples: ["If it rains, we will stay inside.", "If you study, you will pass."],
    quiz_questions: defaultQuiz("First Conditional"),
    xp_reward: 50,
    estimated_minutes: 7,
    published: true,
  },
  {
    slug: "b1-lesson-25-passive",
    title: "Passive Voice",
    description: "Focus on the action, not only the doer.",
    cefr_level: "B1",
    order_index: 25,
    intro_text: "Use passive sentences in formal contexts.",
    word_slugs: ["write", "make", "give", "create", "read"],
    grammar_topic_slug: "passive-voice",
    grammar_tip: "be + past participle: “The email was sent yesterday.”",
    grammar_examples: ["English is spoken here.", "The report was written by Ana."],
    quiz_questions: defaultQuiz("Passive Voice"),
    xp_reward: 50,
    estimated_minutes: 7,
    published: true,
  },
  {
    slug: "b1-lesson-26-comparisons",
    title: "Comparisons in Context",
    description: "Compare options in essays and conversations.",
    cefr_level: "B1",
    order_index: 26,
    intro_text: "Sharper comparisons for clearer arguments.",
    word_slugs: ["big", "small", "different", "important", "easy"],
    grammar_topic_slug: "comparatives-superlatives",
    grammar_tip: "Irregular: good → better → best.",
    grammar_examples: ["This plan is better than the old one.", "She is the most careful."],
    quiz_questions: defaultQuiz("Comparisons in Context"),
    xp_reward: 50,
    estimated_minutes: 7,
    published: true,
  },
  {
    slug: "b2-lesson-27-abstract",
    title: "Abstract Ideas",
    description: "Discuss concepts like justice and freedom.",
    cefr_level: "B2",
    order_index: 27,
    intro_text: "Move beyond concrete objects to ideas.",
    word_slugs: ["concept", "culture", "society", "history", "science"],
    grammar_topic_slug: "relative-clauses",
    grammar_tip: "Which vs that in defining clauses — precision matters.",
    grammar_examples: ["Freedom, which many value, requires responsibility.", "A society that invests in education grows stronger."],
    quiz_questions: defaultQuiz("Abstract Ideas"),
    xp_reward: 60,
    estimated_minutes: 8,
    published: true,
  },
  {
    slug: "b2-lesson-28-formal",
    title: "Formal Writing",
    description: "Tone and structure for essays and emails.",
    cefr_level: "B2",
    order_index: 28,
    intro_text: "Write with a neutral, professional tone.",
    word_slugs: ["article", "evidence", "conclude", "therefore", "however"],
    grammar_topic_slug: "reported-speech",
    grammar_tip: "Avoid contractions in very formal texts.",
    grammar_examples: ["Furthermore, the evidence suggests…", "Therefore, we conclude…"],
    quiz_questions: defaultQuiz("Formal Writing"),
    xp_reward: 60,
    estimated_minutes: 8,
    published: true,
  },
  {
    slug: "b2-lesson-29-emotions-nuanced",
    title: "Nuanced Emotions",
    description: "Describe subtle feelings and attitudes.",
    cefr_level: "B2",
    order_index: 29,
    intro_text: "Go beyond happy/sad with richer vocabulary.",
    word_slugs: ["reluctant", "confident", "frustrated", "grateful", "ambivalent"],
    grammar_topic_slug: "second-conditional",
    grammar_tip: "If + past simple, would + verb for hypothetical present.",
    grammar_examples: ["If I were braver, I would speak up.", "She seemed reluctant to agree."],
    quiz_questions: defaultQuiz("Nuanced Emotions"),
    xp_reward: 60,
    estimated_minutes: 8,
    published: true,
  },
  {
    slug: "b2-lesson-30-hypothetical",
    title: "Hypothetical Situations",
    description: "Discuss unreal scenarios with conditionals.",
    cefr_level: "B2",
    order_index: 30,
    intro_text: "Express imagination and speculation carefully.",
    word_slugs: ["theory", "result", "although", "otherwise", "therefore"],
    grammar_topic_slug: "third-conditional",
    grammar_tip: "If + past perfect, would have + past participle.",
    grammar_examples: ["If we had left earlier, we would have arrived on time."],
    quiz_questions: defaultQuiz("Hypothetical Situations"),
    xp_reward: 60,
    estimated_minutes: 8,
    published: true,
  },
];
